// Tests for the SQL emitter, focused on TABLE, COLUMN, and PRIMARY KEY change
// variants. Other variants (indexes, constraints, views, triggers, policies,
// etc.) are covered elsewhere — except where they ride along inside a
// `TableAdded` payload, since the emitter buckets those into other phases.

use pgpatch::diff::Change;
use pgpatch::emit;
use pgpatch::model::{
    Column, Constraint, Identity, Index, Policy, QualifiedName, Table, Trigger,
};
use std::collections::BTreeMap;

fn qual(schema: &str, name: &str) -> QualifiedName {
    QualifiedName::new(schema, name)
}

fn col(name: &str, ty: &str) -> Column {
    Column {
        name: name.into(),
        data_type: ty.into(),
        nullable: true,
        default: None,
        identity: None,
        generated: None,
        collation: None,
        comment: None,
    }
}

#[test]
fn table_added_plain() {
    let mut t = Table::default();
    t.columns = vec![col("id", "integer"), col("name", "text")];
    let sql = emit::sql(&[Change::TableAdded { qual: qual("public", "users"), table: t }]);
    let expected = "\
CREATE TABLE public.users (
    id integer,
    name text
);
";
    assert_eq!(sql, expected);
}

#[test]
fn table_added_with_primary_key_inline() {
    let mut t = Table::default();
    t.columns = vec![{
        let mut c = col("id", "integer");
        c.nullable = false;
        c
    }];
    t.primary_key = Some(Index {
        definition: "PRIMARY KEY (id)".into(),
        unique: true,
        primary: true,
    });
    let sql = emit::sql(&[Change::TableAdded { qual: qual("public", "t"), table: t }]);
    assert!(sql.contains("CREATE TABLE public.t ("));
    assert!(sql.contains("    id integer NOT NULL"));
    assert!(sql.contains("    PRIMARY KEY (id)"));
    // The PK clause is appended after columns, separated by a comma.
    assert!(sql.contains("NOT NULL,\n    PRIMARY KEY (id)\n);"));
}

#[test]
fn table_added_columns_preserve_vec_order() {
    let mut t = Table::default();
    // Insert in a non-alphabetical order to prove vec order is preserved.
    t.columns = vec![col("zeta", "text"), col("alpha", "text"), col("mu", "text")];
    let sql = emit::sql(&[Change::TableAdded { qual: qual("public", "t"), table: t }]);
    let z = sql.find("zeta").unwrap();
    let a = sql.find("alpha").unwrap();
    let m = sql.find("mu").unwrap();
    assert!(z < a && a < m, "columns should appear in vec order, got:\n{sql}");
}

#[test]
fn column_decl_emits_not_null_default_identity_generated_collation_in_order() {
    // Single column carrying every attribute exercised by column_decl.
    let mut c = col("c", "integer");
    c.nullable = false;
    c.default = Some("0".into());
    c.identity = Some(Identity::Always);
    c.generated = Some("c2 + 1".into()); // pathological, but exercises the code path
    c.collation = Some("C".into());

    let mut t = Table::default();
    t.columns = vec![c];
    let sql = emit::sql(&[Change::TableAdded { qual: qual("public", "t"), table: t }]);

    // Expected order: <name> <type> NOT NULL DEFAULT 0 GENERATED ALWAYS AS IDENTITY GENERATED ALWAYS AS (...) STORED COLLATE "C"
    let line = sql
        .lines()
        .find(|l| l.contains("c integer"))
        .expect("column line not found");
    let nn = line.find("NOT NULL").unwrap();
    let def = line.find("DEFAULT 0").unwrap();
    let id = line.find("GENERATED ALWAYS AS IDENTITY").unwrap();
    let g = line.find("GENERATED ALWAYS AS (c2 + 1) STORED").unwrap();
    let coll = line.find("COLLATE \"C\"").unwrap();
    assert!(nn < def && def < id && id < g && g < coll, "wrong order: {line}");
}

#[test]
fn column_decl_identity_by_default_keyword() {
    let mut c = col("id", "bigint");
    c.nullable = false;
    c.identity = Some(Identity::ByDefault);
    let mut t = Table::default();
    t.columns = vec![c];
    let sql = emit::sql(&[Change::TableAdded { qual: qual("s", "t"), table: t }]);
    assert!(sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
    assert!(!sql.contains("GENERATED ALWAYS AS IDENTITY"));
}

#[test]
fn table_added_buckets_constraints_indexes_triggers_policies_separately() {
    let mut t = Table::default();
    t.columns = vec![{
        let mut c = col("id", "integer");
        c.nullable = false;
        c
    }];
    t.constraints.insert(
        "t_chk".into(),
        Constraint { kind: "CHECK".into(), definition: "CHECK (id > 0)".into() },
    );
    t.indexes.insert(
        "t_idx".into(),
        Index {
            definition: "CREATE INDEX t_idx ON public.t (id)".into(),
            unique: false,
            primary: false,
        },
    );
    t.triggers.insert(
        "t_trg".into(),
        Trigger {
            definition: "CREATE TRIGGER t_trg BEFORE INSERT ON public.t FOR EACH ROW EXECUTE FUNCTION f()".into(),
        },
    );
    t.policies.insert(
        "t_pol".into(),
        Policy {
            command: "ALL".into(),
            permissive: true,
            roles: vec!["PUBLIC".into()],
            qual: Some("true".into()),
            with_check: None,
        },
    );
    t.rls_enabled = true;

    let sql = emit::sql(&[Change::TableAdded { qual: qual("public", "t"), table: t }]);

    // The CREATE TABLE block doesn't carry the indexes/constraints/triggers/
    // policies inline — they're hoisted to their own buckets.
    let create_table_idx = sql.find("CREATE TABLE public.t").unwrap();
    let create_index_idx = sql.find("CREATE INDEX t_idx").unwrap();
    let add_constraint_idx = sql.find("ALTER TABLE public.t ADD CONSTRAINT t_chk").unwrap();
    let create_trigger_idx = sql.find("CREATE TRIGGER t_trg").unwrap();
    let create_policy_idx = sql.find("CREATE POLICY t_pol").unwrap();
    let enable_rls_idx = sql.find("ENABLE ROW LEVEL SECURITY").unwrap();

    // create_tables → create_columns → create_constraints → create_indexes →
    // create_views → create_triggers → create_policies → rls.
    assert!(create_table_idx < add_constraint_idx);
    assert!(add_constraint_idx < create_index_idx);
    assert!(create_index_idx < create_trigger_idx);
    assert!(create_trigger_idx < create_policy_idx);
    assert!(create_policy_idx < enable_rls_idx);

    // The CREATE TABLE block itself has no constraint/index/trigger/policy text.
    let table_block_end = sql[create_table_idx..].find(");").unwrap();
    let table_block = &sql[create_table_idx..create_table_idx + table_block_end];
    assert!(!table_block.contains("CHECK (id > 0)"));
    assert!(!table_block.contains("CREATE INDEX"));
    assert!(!table_block.contains("CREATE TRIGGER"));
    assert!(!table_block.contains("CREATE POLICY"));
}

#[test]
fn table_removed_emits_drop_table() {
    let sql = emit::sql(&[Change::TableRemoved { qual: qual("public", "users") }]);
    assert_eq!(sql, "DROP TABLE public.users;\n");
}

#[test]
fn table_removed_quotes_reserved_and_mixed_case() {
    let sql = emit::sql(&[Change::TableRemoved { qual: qual("Schema", "select") }]);
    // schema "Schema" has uppercase → quoted; "select" is reserved → quoted.
    assert_eq!(sql, "DROP TABLE \"Schema\".\"select\";\n");
}

#[test]
fn column_added_emits_full_column_decl() {
    let mut c = col("email", "text");
    c.nullable = false;
    c.default = Some("'x@y'".into());
    let sql = emit::sql(&[Change::ColumnAdded { table: qual("public", "users"), column: c }]);
    assert_eq!(
        sql,
        "ALTER TABLE public.users ADD COLUMN email text NOT NULL DEFAULT 'x@y';\n"
    );
}

#[test]
fn column_removed_emits_drop_column() {
    let sql = emit::sql(&[Change::ColumnRemoved {
        table: qual("public", "users"),
        name: "email".into(),
    }]);
    assert_eq!(sql, "ALTER TABLE public.users DROP COLUMN email;\n");
}

#[test]
fn column_changed_data_type_only() {
    let before = col("c", "integer");
    let mut after = col("c", "bigint");
    after.nullable = before.nullable;
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    assert_eq!(sql, "ALTER TABLE public.t ALTER COLUMN c TYPE bigint;\n");
}

#[test]
fn column_changed_nullable_set_and_drop() {
    // nullable: true → false ⇒ SET NOT NULL
    let before = col("c", "integer");
    let mut after = col("c", "integer");
    after.nullable = false;
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    assert!(sql.contains("ALTER COLUMN c SET NOT NULL"));

    // nullable: false → true ⇒ DROP NOT NULL
    let mut before = col("c", "integer");
    before.nullable = false;
    let after = col("c", "integer");
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    assert!(sql.contains("ALTER COLUMN c DROP NOT NULL"));
}

#[test]
fn column_changed_default_add_and_drop() {
    // None → Some
    let before = col("c", "integer");
    let mut after = col("c", "integer");
    after.default = Some("42".into());
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    assert!(sql.contains("ALTER COLUMN c SET DEFAULT 42"));

    // Some → None
    let mut before = col("c", "integer");
    before.default = Some("42".into());
    let after = col("c", "integer");
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    assert!(sql.contains("ALTER COLUMN c DROP DEFAULT"));
}

#[test]
fn column_changed_identity_add_and_drop() {
    // None → Some(Always)
    let before = col("c", "integer");
    let mut after = col("c", "integer");
    after.identity = Some(Identity::Always);
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    assert!(sql.contains("ALTER COLUMN c ADD GENERATED ALWAYS AS IDENTITY"));

    // Some → None
    let mut before = col("c", "integer");
    before.identity = Some(Identity::ByDefault);
    let after = col("c", "integer");
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    assert!(sql.contains("ALTER COLUMN c DROP IDENTITY"));
}

#[test]
fn column_changed_identity_mode_swap_emits_todo() {
    let mut before = col("c", "integer");
    before.identity = Some(Identity::Always);
    let mut after = col("c", "integer");
    after.identity = Some(Identity::ByDefault);
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    assert!(sql.contains("-- TODO: change IDENTITY mode"));
}

#[test]
fn column_changed_generated_emits_todo() {
    let mut before = col("c", "integer");
    before.generated = Some("a + 1".into());
    let mut after = col("c", "integer");
    after.generated = Some("a + 2".into());
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    assert!(sql.contains("-- TODO: GENERATED expression changed"));
}

#[test]
fn column_changed_multiple_axes_emits_multiple_statements() {
    // Type change + nullable change + default change all at once.
    let before = col("c", "integer");
    let mut after = col("c", "bigint");
    after.nullable = false;
    after.default = Some("0".into());
    let sql = emit::sql(&[Change::ColumnChanged {
        table: qual("public", "t"),
        name: "c".into(),
        before,
        after,
    }]);
    // All three statements emitted, joined by `\n` within the same bucket entry.
    assert!(sql.contains("ALTER COLUMN c TYPE bigint"));
    assert!(sql.contains("ALTER COLUMN c SET NOT NULL"));
    assert!(sql.contains("ALTER COLUMN c SET DEFAULT 0"));
    // Ordering: type, then nullable, then default (matches code order).
    let t = sql.find("TYPE bigint").unwrap();
    let n = sql.find("SET NOT NULL").unwrap();
    let d = sql.find("SET DEFAULT 0").unwrap();
    assert!(t < n && n < d);
}

#[test]
fn primary_key_added_emits_alter_add() {
    let sql = emit::sql(&[Change::PrimaryKeyAdded {
        table: qual("public", "t"),
        index: Index {
            definition: "PRIMARY KEY (id)".into(),
            unique: true,
            primary: true,
        },
    }]);
    assert_eq!(sql, "ALTER TABLE public.t ADD PRIMARY KEY (id);\n");
}

#[test]
fn primary_key_removed_uses_table_pkey_convention() {
    let sql = emit::sql(&[Change::PrimaryKeyRemoved {
        table: qual("public", "users"),
        index: Index::default(),
    }]);
    assert_eq!(
        sql,
        "ALTER TABLE public.users DROP CONSTRAINT users_pkey;\n"
    );
}

#[test]
fn primary_key_removed_quotes_pkey_when_table_needs_quoting() {
    // Mixed-case table name forces the synthesized `<table>_pkey` to require
    // quoting because of the uppercase letters in `<table>`.
    let sql = emit::sql(&[Change::PrimaryKeyRemoved {
        table: qual("public", "Users"),
        index: Index::default(),
    }]);
    assert_eq!(
        sql,
        "ALTER TABLE public.\"Users\" DROP CONSTRAINT \"Users_pkey\";\n"
    );
}

#[test]
fn primary_key_changed_emits_drop_then_add() {
    let sql = emit::sql(&[Change::PrimaryKeyChanged {
        table: qual("public", "t"),
        before: Index {
            definition: "PRIMARY KEY (id)".into(),
            unique: true,
            primary: true,
        },
        after: Index {
            definition: "PRIMARY KEY (id, tenant_id)".into(),
            unique: true,
            primary: true,
        },
    }]);
    let drop_idx = sql.find("DROP CONSTRAINT t_pkey").expect("drop missing");
    let add_idx = sql.find("ADD PRIMARY KEY (id, tenant_id)").expect("add missing");
    assert!(drop_idx < add_idx, "drop should come before add:\n{sql}");
    // Statements separated by a blank line (i.e. `\n\n`).
    assert!(sql.contains(";\n\nALTER TABLE public.t ADD PRIMARY KEY"));
}

#[test]
fn quote_ident_handles_starts_with_digit_and_reserved() {
    // 1col starts with a digit, "table" is reserved, "Order" is mixed case.
    // Use ColumnRemoved for a compact assertion surface.
    let sql = emit::sql(&[Change::ColumnRemoved {
        table: qual("public", "t"),
        name: "1col".into(),
    }]);
    assert!(sql.contains("DROP COLUMN \"1col\""));

    let sql = emit::sql(&[Change::ColumnRemoved {
        table: qual("public", "t"),
        name: "table".into(),
    }]);
    assert!(sql.contains("DROP COLUMN \"table\""));

    let sql = emit::sql(&[Change::ColumnRemoved {
        table: qual("public", "t"),
        name: "Order".into(),
    }]);
    assert!(sql.contains("DROP COLUMN \"Order\""));
}

#[test]
fn quote_ident_leaves_ordinary_lowercase_unquoted() {
    let sql = emit::sql(&[Change::ColumnRemoved {
        table: qual("public", "user_logins_2024"),
        name: "user_id".into(),
    }]);
    assert_eq!(
        sql,
        "ALTER TABLE public.user_logins_2024 DROP COLUMN user_id;\n"
    );
}

#[test]
fn statements_separated_by_blank_line() {
    // Two TableRemoved should produce two statements separated by an empty
    // line, both terminated with a trailing newline.
    let sql = emit::sql(&[
        Change::TableRemoved { qual: qual("public", "a") },
        Change::TableRemoved { qual: qual("public", "b") },
    ]);
    assert_eq!(sql, "DROP TABLE public.a;\n\nDROP TABLE public.b;\n");
}

#[test]
fn drop_phase_runs_before_create_phase() {
    // DROP TABLE (drop_tables bucket) must precede ADD COLUMN (create_columns
    // bucket) regardless of input order.
    let mut c = col("x", "integer");
    c.nullable = false;
    let sql = emit::sql(&[
        Change::ColumnAdded { table: qual("public", "t"), column: c },
        Change::TableRemoved { qual: qual("public", "old") },
    ]);
    let drop_idx = sql.find("DROP TABLE public.old").unwrap();
    let add_idx = sql.find("ADD COLUMN x").unwrap();
    assert!(drop_idx < add_idx, "drop phase should precede create phase:\n{sql}");
}

// Compile-time guard: keep the `BTreeMap` import live (used implicitly via
// `Table::default`); also ensures we're using the right re-export path.
#[allow(dead_code)]
fn _imports_used() -> BTreeMap<String, String> {
    BTreeMap::new()
}
